#include "token.hpp"
#include "ast.hpp"
#include "parser.hpp"
#include "lexer.hpp"
#include "type_checker.hpp"
#include "symbol_table.hpp"
#include "ir.hpp"
#include "ir_generator.hpp"
#include "optimizer.hpp"
#include "basic_block.hpp"
#include "cfg.hpp"
#include "liveness.hpp"
#include "interference_graph.hpp"
#include "allocator.hpp"
#include "riscv_codegen.hpp"
#include <fstream>
#include <vector>




int main(int argc, char* argv[]){

    //================== ENTIRE PIPELINE =======================//

    //test src code
    // std::string sourceCode = "fn main() -> int { let x: int = 5; send x; }";

    //test src code as a .jkc file input
    if(argc < 2){
        throw std::runtime_error("Usage: compiler <file.jkc>");
    }
    std::ifstream inputFile(argv[1]);

    if(!inputFile){
        throw std::runtime_error("could not open source file");
    }
    std::stringstream buffer;
    buffer << inputFile.rdbuf();
    std::string sourceCode = buffer.str();

    //phase 2: lexer
    LexicalAnalyzer lexer(sourceCode);
    std::vector<Token> tokens = lexer.tokenize();
    printTokens(tokens);

    //phase 3: parser and ast
    Parser ast(tokens);
    //head of the AST
    std::unique_ptr<Program> program = ast.parseProgram();

    //phase 4: symbol table and type checking
    TypeChecker checker;
    checker.checkProgram(*program);

    //phase 5/6

    IRGenerate generator;
    generator.lowerProgram(*program);
    ///////generator.getProgram().print();////////
    IRProgram& irprogram = generator.getProgram(); //use original since irprogram contains unique_ptr's

    //phase 7

    Optimizer optimizer(irprogram);
    optimizer.optimize();
    irprogram.print(); //original gets modified by the optimizer

    //phase 8
    //input: irprogram (optimized)

    //8.1: blocks
    BasicBlockBuilder blockBuilder;
    blockBuilder.buildBlockStruct(irprogram);
    const auto& basicBlocks = blockBuilder.getBasicBlocks();

    //input: basicBlocks
    //8.2: cfg
    CFGBuilder cfgBuilder;
    cfgBuilder.buildCFGs(basicBlocks);
    const auto& cfgs = cfgBuilder.getCFGs();

    //input cfgs
    //8.3: liveness analysis
    LivenessAnalysis liveness;
    liveness.processProgram(cfgs);
    const auto& livenessData = liveness.getData();

    //input livenessData & cfgs
    //8.4: interference graph
    InterferenceGraphBuilder graphBuilder(livenessData);
    graphBuilder.buildProgGraphs(cfgs);
    const auto& graphs = graphBuilder.getProgGraphs();

    //input graphs
    //8.5: reg allocations
    RegisterAllocator allocator(graphs);
    allocator.allocateProgram();
    const auto& allocations = allocator.getAllocations();

    //input allocations, ir program == GGs finished
    //8.6: risc v code gen
    RISCVCodeGenerator codeGenerator(irprogram, allocations);
    codeGenerator.generateProgram();
    std::string assembly = codeGenerator.getAssembly();
    std::cout << "\n=======>GENERATED RISC V<=======\n";
    //PRINT THE FINAL ASM
    std::cout << assembly << std::endl;

    //create .s file for assembling/linking, and QEMU
    std::ofstream asmFile("program.s");
    if(!asmFile){
        throw std::runtime_error("Could not create program.s");
    }
    asmFile << assembly;
    asmFile.close();





    //======================== END PIPELINE ==============================//


    //our IR structure information is stored within irProgramInput.functions



    // std::cout << "src code: " << sourceCode << std::endl << std::endl;

    // std::cout << "tokens generated by  thelexical analyzer:" << std::endl;
    // printTokens(tokens);

    // std::cout << std::endl;
    // std::cout << "ast structure: " << std::endl;
    // program->print();
    return 0;
}