#include "token.hpp"
#include "ast.hpp"
#include "parser.hpp"
#include "lexer.hpp"
#include <vector>




int main(int argc, char* argv[]){

    //test src code
    std::string sourceCode
        = "int main() { int x = 3.14; int y=3.15; "
          "int z=x+y; return 0; }";

    //phase 2: lexer
    LexicalAnalyzer lexer(sourceCode);
    std::vector<Token> tokens = lexer.tokenize();

    //phase 3: parser and ast
    Parser ast(tokens);
    //head of the AST
    std::unique_ptr<Program> program = ast.parseProgram();


    std::cout << "src code: " << sourceCode << std::endl << std::endl;

    std::cout << "tokens generated by  thelexical analyzer:" << std::endl;
    printTokens(tokens);

    std::cout << std::endl;
    std::cout << "ast structure: " << std::endl;
    program->print();
    return 0;
}