#include "token.hpp"
#include "ast.hpp"


int main(int argc, char* argc[]){

    //test src code
    string sourceCode
        = "int main() { float x = 3.14; float y=3.15; "
          "float z=x+y; return 0; }";

    //phase 2: lexer
    LexicalAnalyzer lexer(sourceCode);
    vector<Token> tokens = lexer.tokenize();

    //phase 3: parser and ast
    Parser ast(tokens);
    //head of the AST
    std::unique_ptr<Program> program = ast.parseProgram();


    cout << "src code: " << sourceCode << endl << endl;

    cout << "tokens generated by  thelexical analyzer:" << endl;
    printTokens(tokens);

    cout << endl;
    cout << "ast structure: " << endl;
    program->print();
    return 0;
}